//
//  PCRootViewController.m
//  HitchHike
//
//  Created by Blake on 6/8/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "PCRootViewController.h"


@implementation PCRootViewController

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawRootNavigationBar;
{
    //// General Declarations
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* gradientColor = [UIColor colorWithRed: 0.054 green: 0.091 blue: 0.238 alpha: 1];
    UIColor* gradientColor2 = [UIColor colorWithRed: 0 green: 0.734 blue: 1 alpha: 1];

    //// Gradient Declarations
    CGFloat gradientLocations[] = {0, 0.39, 1};
    CGGradientRef gradient = CGGradientCreateWithColors(colorSpace, (__bridge CFArrayRef)@[(id)gradientColor.CGColor, (id)[UIColor colorWithRed: 0.027 green: 0.412 blue: 0.619 alpha: 1].CGColor, (id)gradientColor2.CGColor], gradientLocations);

    //// Shadow Declarations
    UIColor* outerNavigationBarShadow = [UIColor.blackColor colorWithAlphaComponent: 0.6];
    CGSize outerNavigationBarShadowOffset = CGSizeMake(4.1, -1.1);
    CGFloat outerNavigationBarShadowBlurRadius = 5;

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(320, 0)];
    [bezierPath addCurveToPoint: CGPointMake(320, 102) controlPoint1: CGPointMake(320, -0) controlPoint2: CGPointMake(320, 102)];
    [bezierPath addLineToPoint: CGPointMake(85.77, 102)];
    [bezierPath addCurveToPoint: CGPointMake(62.59, 125.18) controlPoint1: CGPointMake(83.77, 104) controlPoint2: CGPointMake(62.59, 125.18)];
    [bezierPath addCurveToPoint: CGPointMake(39.4, 102) controlPoint1: CGPointMake(62.59, 125.18) controlPoint2: CGPointMake(41.41, 104)];
    [bezierPath addLineToPoint: CGPointMake(0, 102)];
    [bezierPath addLineToPoint: CGPointMake(0, -0)];
    [bezierPath addLineToPoint: CGPointMake(320, -0)];
    [bezierPath addLineToPoint: CGPointMake(320, 0)];
    [bezierPath closePath];
    CGContextSaveGState(context);
    CGContextSetShadowWithColor(context, outerNavigationBarShadowOffset, outerNavigationBarShadowBlurRadius, [outerNavigationBarShadow CGColor]);
    CGContextBeginTransparencyLayer(context, NULL);
    [bezierPath addClip];
    CGContextDrawLinearGradient(context, gradient,
        CGPointMake(219.68, 14.67),
        CGPointMake(86, 128.67),
        kCGGradientDrawsBeforeStartLocation | kCGGradientDrawsAfterEndLocation);
    CGContextEndTransparencyLayer(context);
    CGContextRestoreGState(context);



    //// Cleanup
    CGGradientRelease(gradient);
    CGColorSpaceRelease(colorSpace);
}

+ (void)drawRootTableCell;
{
    //// General Declarations
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* gradientColor = [UIColor colorWithRed: 0.054 green: 0.091 blue: 0.238 alpha: 1];
    UIColor* gradientColor2 = [UIColor colorWithRed: 0 green: 0.734 blue: 1 alpha: 1];

    //// Gradient Declarations
    CGFloat gradientLocations[] = {0, 0.39, 1};
    CGGradientRef gradient = CGGradientCreateWithColors(colorSpace, (__bridge CFArrayRef)@[(id)gradientColor.CGColor, (id)[UIColor colorWithRed: 0.027 green: 0.412 blue: 0.619 alpha: 1].CGColor, (id)gradientColor2.CGColor], gradientLocations);

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(320, 0)];
    [bezierPath addCurveToPoint: CGPointMake(320, 163.44) controlPoint1: CGPointMake(320, -0) controlPoint2: CGPointMake(320, 163.44)];
    [bezierPath addLineToPoint: CGPointMake(87.28, 163.44)];
    [bezierPath addCurveToPoint: CGPointMake(64, 186.78) controlPoint1: CGPointMake(79.16, 171.58) controlPoint2: CGPointMake(64, 186.78)];
    [bezierPath addCurveToPoint: CGPointMake(40.72, 163.44) controlPoint1: CGPointMake(64, 186.78) controlPoint2: CGPointMake(48.84, 171.58)];
    [bezierPath addLineToPoint: CGPointMake(0, 163.44)];
    [bezierPath addLineToPoint: CGPointMake(0, -0)];
    [bezierPath addLineToPoint: CGPointMake(320, -0)];
    [bezierPath addLineToPoint: CGPointMake(320, 0)];
    [bezierPath closePath];
    CGContextSaveGState(context);
    [bezierPath addClip];
    CGContextDrawLinearGradient(context, gradient, CGPointMake(160, -0), CGPointMake(160, 186.78), 0);
    CGContextRestoreGState(context);


    //// Cleanup
    CGGradientRelease(gradient);
    CGColorSpaceRelease(colorSpace);
}

@end
