//
//  PCRootViewController.h
//  HitchHike
//
//  Created by Blake on 6/8/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>


@interface PCRootViewController : NSObject

// Drawing Methods
+ (void)drawRootNavigationBar;
+ (void)drawRootTableCell;

@end
